query Cjenik {
  cjenik {
    kategorije {
      naziv
      slug
      stavke {
        databaseId
        naziv
        vrsta
        cijena
        sidrenaCijena
        sidrenaDatum
        akcija { cijena naziv najniza30Dana }
        jedinicaMjere
        dostupnost
        lokacije {
          objekt
          cijena
          sidrenaCijena
          akcija { cijena naziv najniza30Dana }
          dostupnost
        }
      }
    }
    objekti { id vrsta naziv oblik adresa oznaka }
    datoteke { objekt vrsta lokacija adresa oznaka naziv csv xml objavljeno }
    arhiva { objekt vrsta lokacija adresa oznaka naziv csv xml objavljeno }
  }
}
